# Generated by Django 3.2.7 on 2021-09-04 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('employee_id', models.CharField(max_length=30, unique=True)),
                ('manager', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_manager', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('request_created_at', models.DateTimeField(auto_now_add=True)),
                ('vacation_start_date', models.DateTimeField()),
                ('vacation_end_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='employee.employee')),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolved_by', to='employee.employee')),
            ],
        ),
    ]
